trigger:
  - master
    
pool:
  vmImage: 'ubuntu-latest'

strategy:
  matrix:
    node_8_x:
      node_version: 8.x
    node_10_x:
      node_version: 10.x
    node_12_x:
      node_version: 12.x
    node_13_x:
      node_version: 13.x
      
steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'
    displayName: 'Install Node.js'

  - script: yarn
    displayName: 'Install dependencies'
    
  - script: yarn lint
    displayName: 'Execute lint'

  - script: yarn test:ci
    displayName: 'Execute unit tests'

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testRunner: JUnit
      testResultsFiles: '**/junit.xml'
  
  - task: PublishCodeCoverageResults@1
    inputs: 
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/*cobertura-coverage.xml'
      reportDirectory: '$(System.DefaultWorkingDirectory)/**/coverage'